---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-monitor-ntfy
  namespace: cert-monitor
spec:
  encryptedData:
    NTFY_TOKEN: AgCDqD6KFTwcsmQxWS1ONI8xQHZs596yBn3q1pOpBFjJMnxq3Tz0MZuiKGQXjFLPr29XXQDCXdUCFvAlQtI2HPPwAnfXZCDVV3LxvSVWR4Me8viBdsgBO9tY5HtIOJkyNkrT2SsaOv+2sAWKZGQ31VgAHdJgWrR+usyYLu9Yn1woKsYrwN5YJqaTwORawiU+CDhqorDw0Uqg930JjIidRwbEjmF+AZBriESqEh9hpzjNZOSZU52t8m3BCDfRejUpWMyQCyFwGEf+ajbQzsDt2Zckf+P1YCif7rnR3EALILX00LcINgPHXehAS9HvT7WRtNV9od2qW3AJjwj/xk81/c/4isf1xHe5jksNDLInUVc2Qh2WwvsGVFhRzNTZuY669rjNkjN1who6ovXjW5+tG8nbflBxD5Lbr7nhZtRitdaauNykqV1GWwuksglnk8A2XkIdIvSXgu2+Xi9rFjTD9zNGCVVSO11UMoTNNZs+OEB+iB2LYr5mCQuBdjp9UzvSFdszbRpYed1m/joR/94qC3PLH9hRGCsWFPW+2aUhB+jRwlaPrJ8ut2NorM1xqhYcIv6szGOG4aAW6iyARaXhrBgjlEV8qQGAoHoOa4oIvKczu/ldyqmrNedUr35kYvHXuDTB9WRvyYIPU7bjA0CBSklUhumoOaQ+EPvDPs9RYMf4WSdjKpEEPWVmC7EfbkEnrDoEfiusOPWboM2y7bOaCDNNJuaOTSXxJ/NiySIo9y8BKA==
  template:
    metadata:
      name: cert-monitor-ntfy
      namespace: cert-monitor
